version: '3.5'

services:
  postgres:
    container_name: postgres_adhoc
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-samwayne}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-00000727}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: always
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-samwayne@qq.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-cao418520}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-8880}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
    postgres:
        driver: bridge

volumes:
    postgres:
    pgadmin: